### ISSUE TITLE
Could you provide the command  demo for running?

### ISSUE THREAD

**Issue by Charlie0257** [namsan96/SiMPL#2]
Since I tried to feed the pretrained model to `-s` and there is always something wrong in the code, could you provide the command  demo for running? Thank you very much :)

**Comment by namsan96** [comment]
python simpl_meta_train.py maze_20t  -s spirl_pretrained_maze.pt -g 2 -w 2 2 2 3 3 3

**Comment by namsan96** [comment]
Hi,
Here are example commands :

* Meta-train
Using 40 training tasks
`python simpl_meta_train.py maze_40t -s spirl_pretrained_maze.pt -g 0 -w 0 0 1 1 1`
Using 20 training tasks
`python simpl_meta_train.py maze_20t -s spirl_pretrained_maze.pt -g 0 -w 0 0 1 1 1`

    Note : training is on gpu 0, rollouts are collected from 5 concurrent processes and each will use 0, 0, 1, 1, 1, respectively.

* Fine-tune
`python simpl_fine_tune.py  maze -g 0 -m [output .pt file from simpl_meta_train] -s spirl_pretrained_maze.pt`

Please let me know if you have further issue.

**Comment by Charlie0257** [comment]
Thank you very much! Please update the demo to the README to remind more people :)
